java/jni: Encode four-byte Unicode in `.java` as escaped surrogate pair
When building on Windows the file is assumed to be cp1252 encoded:

```
Main.java:785: error: unmappable character for encoding Cp1252
        x.four_byte_chars_in_str("�??�");
                                   ^
```

Instead of the literals using the `\uXXXX` escape, which requires a surrogate
pair.